import type { Metadata } from "next";

import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { WrapperMiddleware } from "./WrapperMiddleware";
import { IsLogin } from "./IsLogin";
import { NavbarComponent } from "@/components/NavbarComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WrapperMiddleware>
        <IsLogin></IsLogin>
        <body className=" min-h-[100vh] flex flex-col">
          <NavbarComponent></NavbarComponent>
          {children}
        </body>
      </WrapperMiddleware>
    </html>
  );
}
